name: zeely_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/

  fonts:
    - family: Italian Plate No2 Expanded
      fonts:
        - asset: assets/fonts/Italian Plate No2 Expanded Regular.ttf
        - asset: assets/fonts/Italian Plate No2 Expanded Bold.ttf
          weight: 700
